const moviesData = [
 {
    id: 1,
    title: "El Ángel Exterminador",
    director: "Luis Buñuel",
    year: "1962",
    duration: "95 min",
    genre: "Drama / Surrealismo",
    rating: "B15",
    poster: "https://image.tmdb.org/t/p/w500/8tVqHqP2Vb8K2r5lYx1vP28x49s.jpg", 
    backdrop: "https://image.tmdb.org/t/p/original/8tVqHqP2Vb8K2r5lYx1vP28x49s.jpg", 
    synopsis: "Un grupo de burgueses se reúne para una cena en una lujosa mansión tras asistir a la ópera. Al terminar la velada, descubren que, por una razón inexplicable, no pueden salir del salón. A medida que pasan los días, la fachada de civilización se desmorona y surgen los instintos más bajos.",
    cast: ["Silvia Pinal", "Enrique Rambal", "Jacqueline Andere", "José Baviera"],
    trailerId: "v=Xp0N0A0a12w",
    showtimes: ["16:00", "18:30", "21:00"]
  },
  {
    id: 2,
    title: "Amores Perros",
    director: "Alejandro G. Iñárritu",
    year: "2000",
    duration: "154 min",
    genre: "Drama / Thriller",
    rating: "C",
    poster: "https://image.tmdb.org/t/p/w500/3oQ2G5sF8fWk6HhG5A6sT2Q2b1M.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/3oQ2G5sF8fWk6HhG5A6sT2Q2b1M.jpg",
    synopsis: "Tres historias entrelazadas por un fatal accidente automovilístico en la Ciudad de México. Octavio intenta escapar con la esposa de su hermano; Daniel, un editor, deja a su familia por una modelo que resulta gravemente herida en el accidente; y El Chivo, un exguerrillero convertido en sicario, encuentra su redención.",
    cast: ["Gael García Bernal", "Emilio Echevarría", "Goya Toledo", "Álvaro Guerrero"],
    trailerId: "v=qX-g7J-q3n4",
    showtimes: ["15:00", "19:00", "22:00"]
  },
  {
    id: 3,
    title: "Macario",
    director: "Roberto Gavaldón",
    year: "1960",
    duration: "91 min",
    genre: "Fantasía / Drama",
    rating: "A",
    poster: "https://image.tmdb.org/t/p/w500/5k41A235y4oXp4O9XQO92vR9D0c.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/5k41A235y4oXp4O9XQO92vR9D0c.jpg",
    synopsis: "Macario, un aldeano extremadamente pobre y hambriento, anhela comerse un pavo asado él solo. Su esposa roba uno para él. Cuando se dispone a comerlo en el bosque, se le aparecen Dios, el Diablo y la Muerte.",
    cast: ["Ignacio López Tarso", "Pina Pellicer", "Enrique Lucero", "Mario Alberto Rodríguez"],
    trailerId: "v=8g_tZ7wZz30",
    showtimes: ["17:00", "20:00"]
  },
  {
    id: 4,
    title: "Roma",
    director: "Alfonso Cuarón",
    year: "2018",
    duration: "135 min",
    genre: "Drama",
    rating: "B",
    poster: "https://image.tmdb.org/t/p/w500/zS2M1A721W8H7341m9hC6W4Q4r8.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/zS2M1A721W8H7341m9hC6W4Q4r8.jpg",
    synopsis: "Cleo es una joven sirvienta de una familia que vive en la colonia Roma, un barrio de clase media en la Ciudad de México. Alfonso Cuarón entrega un retrato íntimo de las mujeres que lo criaron, ambientado en el turbulento México de la década de 1970.",
    cast: ["Yalitza Aparicio", "Marina de Tavira", "Diego Cortina Autrey", "Carlos Peralta"],
    trailerId: "v=6BS2StcgHlA",
    showtimes: ["14:00", "17:30", "20:45"]
  },
   {
    id: 5,
    title: "Los Olvidados",
    director: "Luis Buñuel",
    year: "1950",
    duration: "80 min",
    genre: "Crimen / Drama",
    rating: "B15",
    poster: "https://image.tmdb.org/t/p/w500/7aZ8v1fL35P2QkP8m6R5pZ3nU5q.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7aZ8v1fL35P2QkP8m6R5pZ3nU5q.jpg",
    synopsis: "Una brutal y cruda mirada a la vida de los niños marginados en los barrios pobres de la Ciudad de México, centrada en un adolescente, El Jaibo, que se escapa de un correccional y arrastra a Pedro, un niño bueno, hacia un trágico destino.",
    cast: ["Alfonso Mejía", "Roberto Cobo", "Estela Inda", "Miguel Inclán"],
    trailerId: "v=4t63o9aY74M",
    showtimes: ["16:30", "19:15"]
  }
]